//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrMinaClinic.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Examination
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Examination()
        {
            this.ExaminationDetails = new HashSet<ExaminationDetail>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int PregnancyId { get; set; }
        public Nullable<int> Weeks { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<int> UterineSize { get; set; }
        public string UrineAlb { get; set; }
        public Nullable<bool> UrineSuger { get; set; }
        public string BP { get; set; }
        public Nullable<int> FundalHeight { get; set; }
        public Nullable<bool> Oedema { get; set; }
        public Nullable<int> Hb { get; set; }
        public Nullable<int> Fhs { get; set; }
        public Nullable<int> Engagement { get; set; }
        public string UltraSoundNotes { get; set; }
        public Nullable<int> No { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExaminationDetail> ExaminationDetails { get; set; }
        public virtual Pregnancy Pregnancy { get; set; }
    }
}
