//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrMinaClinic.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Pregnancies = new HashSet<Pregnancy>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> Twins { get; set; }
        public Nullable<bool> Diabetes { get; set; }
        public Nullable<bool> Hypertension { get; set; }
        public string PastIllness { get; set; }
        public string Operations { get; set; }
        public string Allergies { get; set; }
        public string Drugs { get; set; }
        public string Heart { get; set; }
        public string Lungs { get; set; }
        public string VaricoseVenis { get; set; }
        public string Pelvis { get; set; }
        public string LowerLimbs { get; set; }
        public string PV { get; set; }
        public string AboGroup { get; set; }
        public string RhesusGroup { get; set; }
        public Nullable<bool> CytomegaioVirus { get; set; }
        public Nullable<bool> HbsAg { get; set; }
        public Nullable<bool> HbcAb { get; set; }
        public Nullable<int> Bhcg { get; set; }
        public Nullable<int> EstriolE3 { get; set; }
        public Nullable<int> Fbs { get; set; }
        public Nullable<int> Cbc { get; set; }
        public Nullable<int> Platelets { get; set; }
        public string GeneralRemarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pregnancy> Pregnancies { get; set; }
    }
}
