//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrMinaClinic.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pregnancy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pregnancy()
        {
            this.Examinations = new HashSet<Examination>();
        }
    
        public int Id { get; set; }
        public string PatientId { get; set; }
        public Nullable<int> G { get; set; }
        public Nullable<int> P1 { get; set; }
        public Nullable<int> P2 { get; set; }
        public Nullable<int> Vag { get; set; }
        public Nullable<int> CS { get; set; }
        public Nullable<System.DateTime> LMP { get; set; }
        public Nullable<System.DateTime> EDD { get; set; }
        public Nullable<System.DateTime> ActualBirthdate { get; set; }
        public bool IsCurrent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Examination> Examinations { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
